use crate::connectors::*;
use crate::Connector;

pub fn create_connector(source_type: &str) -> Option<Box<dyn Connector>> {
    match source_type {
        "telegram" => Some(Box::new(telegram::TelegramConnector::new())),
        "discord" => Some(Box::new(discord::DiscordConnector::new())),
        "slack" => Some(Box::new(slack::SlackConnector::new())),
        "whatsapp" => Some(Box::new(whatsapp::WhatsAppConnector::new())),
        "signal" => Some(Box::new(signal::SignalConnector::new())),
        "matrix" => Some(Box::new(matrix::MatrixConnector::new())),
        "email" => Some(Box::new(email::EmailConnector::new())),
        "teams" | "microsoft_teams" => Some(Box::new(teams::TeamsConnector::new())),
        "mattermost" => Some(Box::new(mattermost::MattermostConnector::new())),
        "google_chat" => Some(Box::new(google_chat::GoogleChatConnector::new())),
        "webex" => Some(Box::new(webex::WebexConnector::new())),
        "feishu" | "lark" => Some(Box::new(feishu::FeishuConnector::new())),
        "rocketchat" | "rocket_chat" => Some(Box::new(rocketchat::RocketChatConnector::new())),
        "zulip" => Some(Box::new(zulip::ZulipConnector::new())),
        "xmpp" => Some(Box::new(xmpp::XmppConnector::new())),
        "line" => Some(Box::new(line::LineConnector::new())),
        "viber" => Some(Box::new(viber::ViberConnector::new())),
        "messenger" | "facebook_messenger" => Some(Box::new(messenger::MessengerConnector::new())),
        "mastodon" => Some(Box::new(mastodon::MastodonConnector::new())),
        "bluesky" => Some(Box::new(bluesky::BlueskyConnector::new())),
        "reddit" => Some(Box::new(reddit::RedditConnector::new())),
        "linkedin" => Some(Box::new(linkedin::LinkedInConnector::new())),
        "twitch" => Some(Box::new(twitch::TwitchConnector::new())),
        "irc" => Some(Box::new(irc::IrcConnector::new())),
        "guilded" => Some(Box::new(guilded::GuildedConnector::new())),
        "revolt" => Some(Box::new(revolt::RevoltConnector::new())),
        "keybase" => Some(Box::new(keybase::KeybaseConnector::new())),
        "discourse" => Some(Box::new(discourse::DiscourseConnector::new())),
        "gitter" => Some(Box::new(gitter::GitterConnector::new())),
        "nextcloud_talk" | "nextcloud" => Some(Box::new(nextcloud_talk::NextcloudTalkConnector::new())),
        "threema" => Some(Box::new(threema::ThreemaConnector::new())),
        "nostr" => Some(Box::new(nostr::NostrConnector::new())),
        "mumble" => Some(Box::new(mumble::MumbleConnector::new())),
        "pumble" => Some(Box::new(pumble::PumbleConnector::new())),
        "flock" => Some(Box::new(flock::FlockConnector::new())),
        "twist" => Some(Box::new(twist::TwistConnector::new())),
        "dingtalk" => Some(Box::new(dingtalk::DingTalkConnector::new())),
        "ntfy" => Some(Box::new(ntfy::NtfyConnector::new())),
        "gotify" => Some(Box::new(gotify::GotifyConnector::new())),
        "webhook" => Some(Box::new(webhook::WebhookConnector::new())),
        _ => None,
    }
}

pub fn supported_sources() -> Vec<&'static str> {
    vec![
        "telegram", "discord", "slack", "whatsapp", "signal", "matrix",
        "email", "teams", "mattermost", "google_chat", "webex", "feishu",
        "rocketchat", "zulip", "xmpp", "line", "viber", "messenger",
        "mastodon", "bluesky", "reddit", "linkedin", "twitch", "irc",
        "guilded", "revolt", "keybase", "discourse", "gitter",
        "nextcloud_talk", "threema", "nostr", "mumble", "pumble",
        "flock", "twist", "dingtalk", "ntfy", "gotify", "webhook",
    ]
}

pub fn source_description(source: &str) -> &'static str {
    match source {
        "telegram" => "Telegram Bot API - messages, edits, commands",
        "discord" => "Discord Bot - messages, reactions, threads",
        "slack" => "Slack App - messages, threads, reactions, file uploads",
        "whatsapp" => "WhatsApp Business API - messages, media",
        "signal" => "Signal Messenger - messages, attachments",
        "matrix" => "Matrix protocol - messages, rooms, federation",
        "email" => "Email (IMAP/SMTP) - incoming messages, attachments",
        "teams" => "Microsoft Teams - messages, channels, meetings",
        "mattermost" => "Mattermost - messages, channels, webhooks",
        "google_chat" => "Google Chat - messages, spaces, cards",
        "webex" => "Cisco Webex - messages, rooms, meetings",
        "feishu" => "Feishu/Lark - messages, documents, approvals",
        "rocketchat" => "Rocket.Chat - messages, channels, integrations",
        "zulip" => "Zulip - messages, topics, streams",
        "xmpp" => "XMPP/Jabber - messages, presence, MUC",
        "line" => "LINE Messaging API - messages, stickers, rich menus",
        "viber" => "Viber Bot API - messages, rich media",
        "messenger" => "Facebook Messenger - messages, quick replies, templates",
        "mastodon" => "Mastodon/ActivityPub - toots, boosts, mentions",
        "bluesky" => "Bluesky/AT Protocol - posts, reposts, mentions",
        "reddit" => "Reddit API - posts, comments, subreddits",
        "linkedin" => "LinkedIn API - posts, comments, messages",
        "twitch" => "Twitch IRC/API - chat messages, subscriptions, events",
        "irc" => "IRC protocol - messages, joins, parts, channels",
        "guilded" => "Guilded - messages, channels, reactions",
        "revolt" => "Revolt - messages, channels, servers",
        "keybase" => "Keybase - encrypted messages, teams, channels",
        "discourse" => "Discourse - topics, posts, categories",
        "gitter" => "Gitter - messages, rooms",
        "nextcloud_talk" => "Nextcloud Talk - messages, calls, rooms",
        "threema" => "Threema Gateway - encrypted messages",
        "nostr" => "Nostr protocol - notes, events, relays",
        "mumble" => "Mumble - voice/text messages, channels",
        "pumble" => "Pumble - messages, channels, threads",
        "flock" => "Flock - messages, channels, to-dos",
        "twist" => "Twist - threads, channels, conversations",
        "dingtalk" => "DingTalk - messages, groups, robots",
        "ntfy" => "ntfy - push notifications, topics, subscriptions",
        "gotify" => "Gotify - push messages, applications, priorities",
        "webhook" => "Generic Webhook - HTTP POST events, custom payloads",
        _ => "Unknown connector",
    }
}
